---

- hosts: all
  become: yes
  tasks:
  - name: "Get K3S Install file"
    get_url:
      url: https://get.k3s.io/
      dest: /tmp/install-k3s.sh
      mode: "777"


- hosts: "k3s_init_master"
  tasks:

  - name: "Install K3S Cluster Controller"
  
    shell:
      argv:
      - K3S_KUBECONFIG_MODE=644
      - K3S_TOKEN={{ k3s_token }}
      - INSTALL_K3S_VERSION={{ k3s_version }}
      - /tmp/install-k3s.sh 
      - server 
      - --cluster-init

  - name: "Fetch CA"
    fetch:
      src: "/var/lib/rancher/k3s/server/tls/server-ca.crt"
      dest: output/
      flat: yes
    become: true  

  - name: "Fetch CRT"
    fetch:
      src: "/var/lib/rancher/k3s/server/tls/client-admin.crt"
      dest: "output/"
      flat: yes
    become: true

  - name: "Fetch Key"
    fetch:
      src: "/var/lib/rancher/k3s/server/tls/client-admin.key"
      dest: "output/"
      flat: yes
    become: true  

  - name: "Create kubeconfig file"
    template:
      src: "kubeconfig.j2"
      dest: "output/kubeconfig.yaml"
    delegate_to: "localhost"
  


- hosts: "k3s_masters:!k3s_init_master"
  tasks: 
  - name: "Install K3S Master Set"
    shell:
      argv:
      - K3S_KUBECONFIG_MODE=644
      - K3S_TOKEN={{ k3s_token }}
      - INSTALL_K3S_VERSION={{ k3s_version }}
      - K3S_URL=https://{{ k3s_cluster_controller | default('localhost') }}:6443
      - /tmp/install-k3s.sh
      - server

- hosts: "k3s_nodes"
  tasks: 
  - name: "Install K3S Node"
    shell:
      argv:
      - K3S_KUBECONFIG_MODE=644
      - K3S_TOKEN={{ k3s_token }}
      - INSTALL_K3S_VERSION={{ k3s_version }}
      - K3S_URL=https://{{ k3s_cluster_controller | default('localhost') }}:6443
      - /tmp/install-k3s.sh  

...
